name: aksab_admin
description: "A new Flutter project for Aksab Central Control."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.5.0
  firebase_auth: ^6.2.0
  cloud_firestore: ^6.1.3
  http: ^1.6.0
  image_picker: ^1.2.1
  excel: ^4.0.6
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  cross_file: ^0.3.5+1
  rxdart: ^0.28.0
  intl: ^0.20.2
  pdf: ^3.11.3
  printing: ^5.14.2
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.4
  provider: ^6.1.5+1
  data_table_2: ^2.7.2
  file_picker: ^10.3.10
  flutter_barcode_scanner: ^2.0.0
  image: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # إضافة مكتبة توليد الأيقونات هنا
  flutter_launcher_icons: ^0.13.1

# إعدادات الأيقونات لـ Aksab (أندرويد، iOS، وويب)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/aksab_core_logo.png"
  web:
    generate: true
    image_path: "assets/images/aksab_core_logo.png"
    background_color: "#ffffff"
    theme_color: "#0052cc"

flutter:
  uses-material-design: true

  # تفعيل مسار الصور في المشروع
  assets:
    - assets/images/

