name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - run: flutter pub get

      # 1. تعديل الـ base-href لتكون Root "/"
      - run: flutter build web --release --base-href "/" --no-wasm-dry-run

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          # 2. إضافة اسم الدومين هنا عشان GitHub ميمسحوش
          cname: admin.aksabtech.biz
